### ISSUE TITLE
Bootloop on Android 6.0

### ISSUE THREAD

**Issue by pylerSM** [pylerSM/XInstaller#30]
```
11-14 22:29:16.245   520   520 E Environment: Path requests must specify a user by using UserEnvironment

11-14 22:29:16.245   520   520 E Environment: java.lang.Throwable

11-14 22:29:16.245   520   520 E Environment: 	at android.os.Environment.throwIfUserRequired(Environment.java:743)

11-14 22:29:16.245   520   520 E Environment: 	at android.os.Environment.getExternalStorageDirectory(Environment.java:336)

11-14 22:29:16.245   520   520 E Environment: 	at com.pyler.xinstaller.Common.<clinit>(Common.java:96)

11-14 22:29:16.245   520   520 E Environment: 	at com.pyler.xinstaller.XInstaller.handleLoadPackage(XInstaller.java:1184)

11-14 22:29:16.245   520   520 E Environment: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)

11-14 22:29:16.245   520   520 E Environment: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)

11-14 22:29:16.245   520   520 E Environment: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)

11-14 22:29:16.245   520   520 E Environment: 	at de.robv.android.xposed.XposedBridge$3$1.beforeHookedMethod(XposedBridge.java:215)

11-14 22:29:16.245   520   520 E Environment: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)

11-14 22:29:16.245   520   520 E Environment: 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)

11-14 22:29:16.245   520   520 E Environment: 	at com.android.server.SystemServer.run(SystemServer.java:268)

11-14 22:29:16.245   520   520 E Environment: 	at com.android.server.SystemServer.main(SystemServer.java:168)

11-14 22:29:16.245   520   520 E Environment: 	at java.lang.reflect.Method.invoke(Native Method)

11-14 22:29:16.245   520   520 E Environment: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

11-14 22:29:16.245   520   520 E Environment: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

11-14 22:29:16.245   520   520 E Environment: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

11-14 22:29:16.246   520   520 E AndroidRuntime: Error reporting WTF

11-14 22:29:16.246   520   520 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.app.IActivityManager.handleApplicationWtf(android.os.IBinder, java.lang.String, boolean, android.app.ApplicationErrorReport$CrashInfo)' on a null object reference

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.wtf(RuntimeInit.java:348)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at android.util.Log$1.onTerribleFailure(Log.java:104)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:297)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:286)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at android.os.Environment.throwIfUserRequired(Environment.java:742)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at android.os.Environment.getExternalStorageDirectory(Environment.java:336)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at com.pyler.xinstaller.Common.<clinit>(Common.java:96)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at com.pyler.xinstaller.XInstaller.handleLoadPackage(XInstaller.java:1184)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge$3$1.beforeHookedMethod(XposedBridge.java:215)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:268)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:168)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

11-14 22:29:16.246   520   520 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

11-14 22:29:16.247   520   520 E AndroidRuntime: Original WTF:

11-14 22:29:16.247   520   520 E AndroidRuntime: android.util.Log$TerribleFailure: Path requests must specify a user by using UserEnvironment

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:291)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:286)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at android.os.Environment.throwIfUserRequired(Environment.java:742)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at android.os.Environment.getExternalStorageDirectory(Environment.java:336)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at com.pyler.xinstaller.Common.<clinit>(Common.java:96)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at com.pyler.xinstaller.XInstaller.handleLoadPackage(XInstaller.java:1184)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge$3$1.beforeHookedMethod(XposedBridge.java:215)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:268)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:168)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

11-14 22:29:16.247   520   520 E AndroidRuntime: Caused by: java.lang.Throwable

11-14 22:29:16.247   520   520 E AndroidRuntime: 	at android.os.Environment.throwIfUserRequired(Environment.java:743)

11-14 22:29:16.247   520   520 E AndroidRuntime: 	... 15 more

11-14 22:29:16.248   520   520 E Xposed  : java.lang.ExceptionInInitializerError

11-14 22:29:16.248   520   520 E Xposed  : 	at com.pyler.xinstaller.XInstaller.handleLoadPackage(XInstaller.java:1184)

11-14 22:29:16.248   520   520 E Xposed  : 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)

11-14 22:29:16.248   520   520 E Xposed  : 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)

11-14 22:29:16.248   520   520 E Xposed  : 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)

11-14 22:29:16.248   520   520 E Xposed  : 	at de.robv.android.xposed.XposedBridge$3$1.beforeHookedMethod(XposedBridge.java:215)

11-14 22:29:16.248   520   520 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)

11-14 22:29:16.248   520   520 E Xposed  : 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)

11-14 22:29:16.248   520   520 E Xposed  : 	at com.android.server.SystemServer.run(SystemServer.java:268)

11-14 22:29:16.248   520   520 E Xposed  : 	at com.android.server.SystemServer.main(SystemServer.java:168)

11-14 22:29:16.248   520   520 E Xposed  : 	at java.lang.reflect.Method.invoke(Native Method)

11-14 22:29:16.248   520   520 E Xposed  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

11-14 22:29:16.248   520   520 E Xposed  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

11-14 22:29:16.248   520   520 E Xposed  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

11-14 22:29:16.248   520   520 E Xposed  : Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.content.pm.IPackageManager.getPackageUid(java.lang.String, int)' on a null object reference

11-14 22:29:16.248   520   520 E Xposed  : 	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:879)

11-14 22:29:16.248   520   520 E Xposed  : 	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:83)

11-14 22:29:16.248   520   520 E Xposed  : 	at android.os.Environment.getExternalStorageDirectory(Environment.java:337)

11-14 22:29:16.248   520   520 E Xposed  : 	at com.pyler.xinstaller.Common.<clinit>(Common.java:96)

11-14 22:29:16.248   520   520 E Xposed  : 	... 13 more
```

**Comment by pylerSM** [comment]
Full log: http://www9.zippyshare.com/v/YFDuH5AA/file.html

@rovo89

**Comment by pylerSM** [comment]
Should we patch throwIfUserRequired to just do nothing and be silent?

**Comment by rovo89** [comment]
No, please try to disable your module first. It seems to cause the bootloop.

**Comment by pylerSM** [comment]
Well, this is not solution since I want to port it for 6.0. And by default, all options are off. This is the root cause of the issue.

**Comment by rovo89** [comment]
Does it boot without your module or not?

**Comment by pylerSM** [comment]
Yep, no issue.

**Comment by rovo89** [comment]
There you have it. Get rid of the getExternalStorageDirectory() call in your Common class and you'll probably be fine. The log says it all "Path requests must specify a user by using UserEnvironment". This method actually requires that a user is logged on because each user will have their own storage.

You have wasted enough of my time. Goodbye.

**Comment by pylerSM** [comment]
Don't be so rude, please.

**Comment by pylerSM** [comment]
I define it in Common class
https://github.com/pylerSM/XInstaller/blob/d169ea4e4890a5b94224b1c0fd1596584d7aa8a2/src/com/pyler/xinstaller/Common.java#L119


and use it in broadcast receiver: https://github.com/pylerSM/XInstaller/blob/6af667dd8bab924eb790b744cbff31170c7c99c9/src/com/pyler/xinstaller/Utils.java#L80

but... nothing to say.

**Comment by pylerSM** [comment]
Anyway, I got same errors on Lollipop it didn't cause bootloop.

**Comment by pylerSM** [comment]
```
11-15 01:12:11.777   508  3985 E Xposed  : java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

11-15 01:12:11.777   508  3985 E Xposed  : 	at java.lang.Thread.nativeCreate(Native Method)

11-15 01:12:11.777   508  3985 E Xposed  : 	at java.lang.Thread.start(Thread.java:1063)

11-15 01:12:11.777   508  3985 E Xposed  : 	at de.robv.android.xposed.XSharedPreferences.startLoadFromDisk(XSharedPreferences.java:108)

11-15 01:12:11.777   508  3985 E Xposed  : 	at de.robv.android.xposed.XSharedPreferences.reload(XSharedPreferences.java:163)

11-15 01:12:11.777   508  3985 E Xposed  : 	at com.pyler.xinstaller.XInstaller.isModuleEnabled(XInstaller.java:1481)

11-15 01:12:11.777   508  3985 E Xposed  : 	at com.pyler.xinstaller.XInstaller$100000006.beforeHookedMethod(XInstaller.java:303)

11-15 01:12:11.777   508  3985 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)

11-15 01:12:11.777   508  3985 E Xposed  : 	at com.android.server.pm.PackageManagerService.getPackageInfo(<Xposed>)

11-15 01:12:11.777   508  3985 E Xposed  : 	at com.android.server.am.ActivityManagerService.appendDropBoxProcessHeaders(ActivityManagerService.java:12352)

11-15 01:12:11.777   508  3985 E Xposed  : 	at com.android.server.am.ActivityManagerService.logStrictModeViolationToDropBox(ActivityManagerService.java:12147)

11-15 01:12:11.777   508  3985 E Xposed  : 	at com.android.server.am.ActivityManagerService.handleApplicationStrictModeViolation(ActivityManagerService.java:12095)

11-15 01:12:11.777   508  3985 E Xposed  : 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1480)

11-15 01:12:11.777   508  3985 E Xposed  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2443)

11-15 01:12:11.777   508  3985 E Xposed  : 	at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by easyaspi314** [comment]
I am on CM13 now (yay) so I can help test this.

**Comment by pylerSM** [comment]
Okey, thanks

**Comment by pylerSM** [comment]
com.google.android.packageinstaller
