### ISSUE TITLE
Disable signature checking only partially works

### ISSUE THREAD

**Issue by Lanchon** [pylerSM/XInstaller#40]
hi,

in "Installations", disable signature check works fine for installations.

in "Misc", disable verify signatures does not seem to work under android 4.4, at least partially. though apps are started, they cannot use `ClassLoader.getResourceAsStream` which makes most apps fail:

```
java.lang.SecurityException: Incorrect signature
     at org.apache.harmony.security.utils.JarUtils.verifySignature(JarUtils.java:232)
     at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:306)
     at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:276)
     at java.util.jar.JarFile.getInputStream(JarFile.java:399)
     at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
     at java.net.URL.openStream(URL.java:470)
     at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:432)
```

**Comment by pylerSM** [comment]
Option is enabled? Expert mode is enabled too?

**Comment by Lanchon** [comment]
yes and yes. options are enabled while running the altered app.

would you want me to test this again on android 6.0.1?

**Comment by Daemonceltics** [comment]
hi, I select disable checking signatures and F-Droid option ， but apk that I changed resource file install error 
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
device:nexus 5 Android4.4

**Comment by Jasi2169** [comment]
@pylerSM from android 7 it wont work apk signed with apk signature verification 2
